"""Initial ignore policy (SD §6 step 1, spec §5.1)."""

from collections.abc import Callable

import pytest

from app.review.filtering import (
    CandidateFile,
    IgnorePolicy,
    apply_ignore_policy,
    file_path,
)
from app.review.schemas.context import FileDiff, SkipReason


@pytest.mark.parametrize(
    "path",
    [
        "uv.lock",
        "web/package-lock.json",
        "pnpm-lock.yaml",
        "poetry.lock",
        "static/app.min.js",
        "static/app.min.css",
        "dist/bundle.js",
        "web/dist/bundle.js",
        "vendor/lib/a.go",
        "tests/__snapshots__/view.snap",
        "proto/api_pb2.py",
        "proto/api.pb.go",
    ],
)
def test_default_policy_skips_generated_and_lock_files(
    make_diff: Callable[..., FileDiff], path: str
) -> None:
    result = apply_ignore_policy([CandidateFile(make_diff(path))])

    assert result.kept == []
    assert [(s.path, s.reason) for s in result.skipped] == [(path, SkipReason.POLICY)]


@pytest.mark.parametrize(
    "path",
    ["src/app/main.py", "migrations/versions/0002_add.py", "docs/distribution.md"],
)
def test_source_and_migrations_are_kept(
    make_diff: Callable[..., FileDiff], path: str
) -> None:
    result = apply_ignore_policy([CandidateFile(make_diff(path))])

    assert [file_path(d) for d in result.kept] == [path]


def test_binary_and_generated_header_files_are_skipped(
    make_diff: Callable[..., FileDiff],
) -> None:
    files = [
        CandidateFile(make_diff("assets/logo.png"), is_binary=True),
        CandidateFile(
            make_diff(
                "src/api_client.py", text="# Code generated by openapi. DO NOT EDIT."
            )
        ),
        CandidateFile(make_diff("src/models.ts", text="// @generated")),
    ]

    result = apply_ignore_policy(files)

    assert result.kept == []
    assert {s.reason for s in result.skipped} == {SkipReason.POLICY}


def test_extra_globs_extend_the_policy(make_diff: Callable[..., FileDiff]) -> None:
    policy = IgnorePolicy(extra_globs=("fixtures/**",))

    result = apply_ignore_policy([CandidateFile(make_diff("fixtures/a.py"))], policy)

    assert result.kept == []
