"""Initial ignore policy (SD §6 step 1, spec §5.1).

Migrations are deliberately not excluded: they can change data and schema.
Repository overrides and the ``admin`` role are out of scope; ``extra_globs``
is the hook for them.
"""

import re
from dataclasses import dataclass, field
from pathlib import PurePosixPath

from app.review.schemas.context import FileDiff, SkippedItem, SkipReason

DEFAULT_GLOBS = (
    "*.lock",
    "package-lock.json",
    "pnpm-lock.yaml",
    "poetry.lock",
    "*.min.js",
    "*.min.css",
    "dist/**",
    "vendor/**",
    "*.snap",
    "*_pb2.py",
    "*.pb.go",
)

# Recognized generated-file markers, searched in the first lines of a file.
_GENERATED_HEADER = re.compile(
    r"@generated|do not edit|auto-generated|autogenerated", re.IGNORECASE
)
_HEADER_LINES = 5


@dataclass(frozen=True)
class IgnorePolicy:
    version: str = "ignore-v1"
    globs: tuple[str, ...] = DEFAULT_GLOBS
    extra_globs: tuple[str, ...] = ()

    def matches(self, path: str) -> bool:
        pure = PurePosixPath(path)
        for pattern in (*self.globs, *self.extra_globs):
            if "/" not in pattern:
                if pure.match(pattern):  # file name at any depth
                    return True
            elif pure.full_match(pattern) or pure.full_match(f"**/{pattern}"):
                return True
        return False


@dataclass(frozen=True)
class CandidateFile:
    """A changed file as delivered by the VCS adapter."""

    diff: FileDiff
    is_binary: bool = False


@dataclass(frozen=True)
class FilterResult:
    kept: list[FileDiff] = field(default_factory=list)
    skipped: list[SkippedItem] = field(default_factory=list)


def file_path(diff: FileDiff) -> str:
    """The path a file is known by: new path, or old path for deletions."""
    path = diff.new_path or diff.old_path
    if path is None:
        msg = f"file {diff.file_id} has neither old nor new path"
        raise ValueError(msg)
    return path


def apply_ignore_policy(
    files: list[CandidateFile], policy: IgnorePolicy | None = None
) -> FilterResult:
    policy = policy or IgnorePolicy()
    result = FilterResult()
    for candidate in files:
        path = file_path(candidate.diff)
        if candidate.is_binary or policy.matches(path) or _is_generated(candidate.diff):
            result.skipped.append(SkippedItem(path=path, reason=SkipReason.POLICY))
        else:
            result.kept.append(candidate.diff)
    return result


def _is_generated(diff: FileDiff) -> bool:
    """Only the diff is available: look at its lines from the top of the file."""
    for hunk in diff.hunks:
        for line in hunk.lines:
            number = line.new_line or line.old_line
            is_header = number is not None and number <= _HEADER_LINES
            if is_header and _GENERATED_HEADER.search(line.text):
                return True
    return False
